In [26]:
import pandas as pd

## 2011년 엑셀데이터를 정제된 csv파일로
- 컬럼이름을 바꾸기
- 엑셀데이터를 받으면서 불필요한 부분 인덱스 삭제
- 종목명을 가지고 오름차순 정렬
- shape(668,6)

In [27]:
df=pd.read_excel('./ESG_excel/2011.xlsx')
df.columns=['종목명','ESG 통합등급','2011_E','2011_S','2011_G','평가연도']
df_2011=df.iloc[4:,:].reset_index(drop=True)
df_2011.sort_values("종목명",inplace=True)
df_2011
#df_2011.to_csv("2011.csv",index=False,encoding='euc-kr')

           종목명 ESG 통합등급 2011_E 2011_S 2011_G  평가연도
0        AK홀딩스      B이하      B    B이하    B이하  2011
1          BYC      B이하      B    B이하    B이하  2011
2           CJ      B이하     B+    B이하    NaN  2011
3       CJ CGV      B이하      B    B이하    NaN  2011
4       CJ대한통운       B+      B     B+    B이하  2011
..         ...      ...    ...    ...    ...   ...
299  휴니드테크놀러지스       B+      C     B+    B이하  2011
300        휴스틸      NaN      B    NaN    B이하  2011
301        휴켐스      B이하     B+    B이하     B+  2011
302       흥국화재      B이하      C    B이하    NaN  2011
303       흥아해운      B이하      B    B이하    NaN  2011

[668 rows x 6 columns]

In [48]:
pd.read_csv('./ESG_csv/2011.csv',encoding='euc-kr')

           종목명 ESG 통합등급 2011_E 2011_S 2011_G  평가연도
0        AK홀딩스      B이하      B    B이하    B이하  2011
1          BYC      B이하      B    B이하    B이하  2011
2           CJ      B이하     B+    B이하    NaN  2011
3       CJ CGV      B이하      B    B이하    NaN  2011
4       CJ대한통운       B+      B     B+    B이하  2011
..         ...      ...    ...    ...    ...   ...
663  휴니드테크놀러지스       B+      C     B+    B이하  2011
664        휴스틸      NaN      B    NaN    B이하  2011
665        휴켐스      B이하     B+    B이하     B+  2011
666       흥국화재      B이하      C    B이하    NaN  2011
667       흥아해운      B이하      B    B이하    NaN  2011

[668 rows x 6 columns]

## 2012년 엑셀데이터를 정제된 csv파일로
- 컬럼이름을 바꾸기
- 엑셀데이터를 받으면서 불필요한 부분 인덱스 삭제
- 종목명을 가지고 오름차순 정렬
- 리셋 인덱스도 해줬다
- shape(710,6)

In [28]:
df=pd.read_excel('./ESG_excel/2012.xlsx')
df.columns=['종목명','ESG 통합등급','2012_E','2012_S','2012_G','평가연도']
df_2012=df.iloc[4:,:].reset_index(drop=True)
df_2012.sort_values("종목명",inplace=True)
df_2012.reset_index(drop=True,inplace=True)
df_2012
#df_2012.to_csv("2012.csv",index=False,encoding='euc-kr')

           종목명 ESG 통합등급 2012_E 2012_S 2012_G  평가연도
0        AK홀딩스      B이하      C    B이하     B+  2012
1      BNK금융지주        A     A+      A    B이하  2012
2          BYC      B이하      C    B이하    B이하  2012
3           CJ      B이하      B    B이하    B이하  2012
4       CJ CGV      B이하      B    B이하    B이하  2012
..         ...      ...    ...    ...    ...   ...
705  휴니드테크놀러지스      B이하      C    B이하    B이하  2012
706        휴스틸      B이하      B    B이하     B+  2012
707        휴켐스       B+      B     B+     B+  2012
708       흥국화재      B이하      B    B이하    B이하  2012
709       흥아해운      B이하      B    B이하    B이하  2012

[710 rows x 6 columns]

## 2013년 엑셀데이터를 정제된 csv파일로
- 컬럼이름을 바꾸기
- 엑셀데이터를 받으면서 불필요한 부분 인덱스 삭제
- 종목명을 가지고 오름차순 정렬
- 리셋 인덱스도 해줬다
- shape(693,6)

In [29]:
df=pd.read_excel('./ESG_excel/2013.xlsx')
df.columns=['종목명','ESG 통합등급','2013_E','2013_S','2013_G','평가연도']
df_2013=df.iloc[4:,:].reset_index(drop=True)
df_2013.sort_values("종목명",inplace=True)
df_2013.reset_index(drop=True,inplace=True)
df_2013
#df_2013.to_csv("2013.csv",index=False,encoding='euc-kr')

           종목명 ESG 통합등급 2013_E 2013_S 2013_G  평가연도
0        AK홀딩스      B이하      C    B이하    B이하  2013
1      BNK금융지주       B+      A      A    B이하  2013
2          BYC      B이하      B    B이하    B이하  2013
3           CJ       B+      B      A    B이하  2013
4       CJ CGV      B이하      B    B이하    B이하  2013
..         ...      ...    ...    ...    ...   ...
688  휴니드테크놀러지스      B이하      B    B이하    B이하  2013
689        휴스틸      B이하      B    B이하    B이하  2013
690        휴켐스       B+      B     B+     B+  2013
691       흥국화재      B이하      B    B이하    B이하  2013
692       흥아해운      B이하      B    B이하    B이하  2013

[693 rows x 6 columns]

## 2014년 엑셀데이터를 정제된 csv파일로
- 컬럼이름을 바꾸기
- 엑셀데이터를 받으면서 불필요한 부분 인덱스 삭제
- 종목명을 가지고 오름차순 정렬
- 리셋 인덱스도 해줬다
- shape(694,6)

In [30]:
df=pd.read_excel('./ESG_excel/2014.xlsx')
df.columns=['종목명','ESG 통합등급','2014_E','2014_S','2014_G','평가연도']
df_2014=df.iloc[4:,:].reset_index(drop=True)
df_2014.sort_values("종목명",inplace=True)
df_2014.reset_index(drop=True,inplace=True)
df_2014
#df_2014.to_csv("2014.csv",index=False,encoding='euc-kr')

         종목명 ESG 통합등급 2014_E 2014_S 2014_G  평가연도
0      AJ렌터카      B이하      C    B이하    B이하  2014
1      AK홀딩스      B이하      C    B이하    B이하  2014
2    BNK금융지주        A     A+      A    B이하  2014
3        BYC      B이하      C    B이하    B이하  2014
4         CJ       B+      B      A     B+  2014
..       ...      ...    ...    ...    ...   ...
689      휴비스      B이하      C    B이하    B이하  2014
690      휴스틸      B이하      B    B이하     B+  2014
691      휴켐스       B+      B     B+     B+  2014
692     흥국화재      B이하      B    B이하    B이하  2014
693     흥아해운      B이하      B    B이하    B이하  2014

[694 rows x 6 columns]

## 2015년 엑셀데이터를 정제된 csv파일로
- 컬럼이름을 바꾸기
- 엑셀데이터를 받으면서 불필요한 부분 인덱스 삭제
- 종목명을 가지고 오름차순 정렬
- 리셋 인덱스도 해줬다
- shape(696,6)

In [31]:
df=pd.read_excel('./ESG_excel/2015.xlsx')
df.columns=['종목명','ESG 통합등급','2015_E','2015_S','2015_G','평가연도']
df_2015=df.iloc[4:,:].reset_index(drop=True)
df_2015.sort_values("종목명",inplace=True)
df_2015.reset_index(drop=True,inplace=True)
df_2015
#df_2015.to_csv("2015.csv",index=False,encoding='euc-kr')

         종목명 ESG 통합등급 2015_E 2015_S 2015_G  평가연도
0      AJ렌터카      B이하      C    B이하    B이하  2015
1      AK홀딩스      B이하      C    B이하    B이하  2015
2    BNK금융지주        A     A+      A    B이하  2015
3        BYC      B이하      C    B이하    B이하  2015
4         CJ       B+      B      A     B+  2015
..       ...      ...    ...    ...    ...   ...
691      휴비스      B이하      C    B이하    B이하  2015
692      휴스틸      B이하      B    B이하     B+  2015
693      휴켐스      B이하      B    B이하     B+  2015
694     흥국화재      B이하     B+    B이하    B이하  2015
695     흥아해운      B이하      B    B이하    B이하  2015

[696 rows x 6 columns]

## 2016년 엑셀데이터를 정제된 csv파일로
- 컬럼이름을 바꾸기
- 엑셀데이터를 받으면서 불필요한 부분 인덱스 삭제
- 종목명을 가지고 오름차순 정렬
- 리셋 인덱스도 해줬다
- shape(713,6)

In [32]:
df=pd.read_excel('./ESG_excel/2016.xlsx')
df.columns=['종목명','ESG 통합등급','2016_E','2016_S','2016_G','평가연도']
df_2016=df.iloc[4:,:].reset_index(drop=True)
df_2016.sort_values("종목명",inplace=True)
df_2016.reset_index(drop=True,inplace=True)
df_2016
#df_2016.to_csv("2016.csv",index=False,encoding='euc-kr')

         종목명 ESG 통합등급 2016_E 2016_S 2016_G  평가연도
0     AJ네트웍스      B이하      C    B이하    B이하  2016
1      AJ렌터카      B이하      C    B이하    B이하  2016
2      AK홀딩스      B이하      B    B이하    B이하  2016
3        BGF      B이하      B     B+    B이하  2016
4    BNK금융지주        A     A+     B+    B이하  2016
..       ...      ...    ...    ...    ...   ...
708      휴비스       B+      B     B+     B+  2016
709      휴스틸      B이하      B    B이하     B+  2016
710      휴켐스       B+      B     B+      A  2016
711     흥국화재       B+     A+    B이하    B이하  2016
712     흥아해운      B이하      C    B이하    B이하  2016

[713 rows x 6 columns]

## 2017년 엑셀데이터를 정제된 csv파일로
- 컬럼이름을 바꾸기
- 엑셀데이터를 받으면서 불필요한 부분 인덱스 삭제
- 종목명을 가지고 오름차순 정렬
- 리셋 인덱스도 해줬다
- shape(733,6)

In [33]:
df=pd.read_excel('./ESG_excel/2017.xlsx')
df.columns=['종목명','ESG 통합등급','2017_E','2017_S','2017_G','평가연도']
df_2017=df.iloc[4:,:].reset_index(drop=True)
df_2017.sort_values("종목명",inplace=True)
df_2017.reset_index(drop=True,inplace=True)
df_2017.reset_index(drop=True,inplace=True)
df_2017
#df_2017.to_csv("2017.csv",index=False,encoding='euc-kr')

         종목명 ESG 통합등급 2017_E 2017_S 2017_G  평가연도
0     AJ네트웍스      B이하      B    B이하    B이하  2017
1      AJ렌터카      B이하      C    B이하    B이하  2017
2      AK홀딩스      B이하      B    B이하    B이하  2017
3        BGF      B이하      B      A    B이하  2017
4    BNK금융지주       B+      B      A     B+  2017
..       ...      ...    ...    ...    ...   ...
728      휴비스       B+      B      A     B+  2017
729      휴스틸      B이하      B    B이하    B이하  2017
730      휴켐스       B+      B     B+     B+  2017
731     흥국화재       B+      A    B이하    B이하  2017
732     흥아해운      B이하      B    B이하    B이하  2017

[733 rows x 6 columns]

## 2018년 엑셀데이터를 정제된 csv파일로
- 컬럼이름을 바꾸기
- 엑셀데이터를 받으면서 불필요한 부분 인덱스 삭제
- 종목명을 가지고 오름차순 정렬
- 리셋 인덱스도 해줬다
- shape(747,6)

In [34]:
df=pd.read_excel('./ESG_excel/2018.xlsx')
df.columns=['종목명','ESG 통합등급','2018_E','2018_S','2018_G','평가연도']
df_2018=df.iloc[4:,:].reset_index(drop=True)
df_2018.sort_values("종목명",inplace=True)
df_2018.reset_index(drop=True,inplace=True)
df_2018.reset_index(drop=True,inplace=True)
df_2018
#df_2018.to_csv("2018.csv",index=False,encoding='euc-kr')

         종목명 ESG 통합등급 2018_E 2018_S 2018_G  평가연도
0     AJ네트웍스      B이하      C    B이하    B이하  2018
1      AJ렌터카      B이하      B    B이하     B+  2018
2      AK홀딩스      B이하      C    B이하    B이하  2018
3        BGF      NaN      B    NaN    NaN  2018
4    BNK금융지주       B+  B+ 이하     B+    B이하  2018
..       ...      ...    ...    ...    ...   ...
742      휴비스       B+     B+     B+     B+  2018
743      휴스틸      B이하      B    B이하    B이하  2018
744      휴켐스      B이하      B    B이하     B+  2018
745     흥국화재      B이하  B+ 이하    B이하    B이하  2018
746     흥아해운      B이하      C    B이하    B이하  2018

[747 rows x 6 columns]

## 각년도들 별로 컬럼당 결측치 확인하기

In [50]:
df_2011=pd.read_csv('./ESG_csv/2011.csv',encoding='euc-kr',index_col='종목명')
print(df_2011.isna().sum())

ESG 통합등급    136
2011_E        0
2011_S      137
2011_G      296
평가연도          0
dtype: int64

In [51]:
df_2012=pd.read_csv('./ESG_csv/2012.csv',encoding='euc-kr',index_col='종목명')
print(df_2012.isna().sum())

ESG 통합등급    45
2012_E       4
2012_S       4
2012_G      37
평가연도         0
dtype: int64

In [52]:
df_2013=pd.read_csv('./ESG_csv/2013.csv',encoding='euc-kr',index_col='종목명')
print(df_2013.isna().sum())

ESG 통합등급    0
2013_E      0
2013_S      0
2013_G      0
평가연도        0
dtype: int64

In [53]:
df_2014=pd.read_csv('./ESG_csv/2014.csv',encoding='euc-kr',index_col='종목명')
print(df_2014.isna().sum())

ESG 통합등급    0
2014_E      0
2014_S      0
2014_G      0
평가연도        0
dtype: int64

In [54]:
df_2015=pd.read_csv('./ESG_csv/2015.csv',encoding='euc-kr',index_col='종목명')
print(df_2015.isna().sum())

ESG 통합등급    0
2015_E      0
2015_S      0
2015_G      0
평가연도        0
dtype: int64

In [55]:
df_2016=pd.read_csv('./ESG_csv/2016.csv',encoding='euc-kr',index_col='종목명')
print(df_2016.isna().sum())

ESG 통합등급    0
2016_E      0
2016_S      0
2016_G      0
평가연도        0
dtype: int64

In [57]:
df_2017=pd.read_csv('./ESG_csv/2017.csv',encoding='euc-kr',index_col='종목명')
print(df_2017.isna().sum())

ESG 통합등급    0
2017_E      0
2017_S      0
2017_G      0
평가연도        0
dtype: int64

In [58]:
df_2018=pd.read_csv('./ESG_csv/2018.csv',encoding='euc-kr',index_col='종목명')
print(df_2018.isna().sum())

ESG 통합등급    20
2018_E       0
2018_S      20
2018_G      20
평가연도         0
dtype: int64

### 결측치가 너무 많은 2011년은 train_set에서 제외하고, 2012~2018년까지 train_set으로 이용