In [68]:
import pandas as pd

## Origin 1213데이터 만들기

In [69]:
list_1=pd.read_csv('./df_add_job/df_1213_add_job.csv')

In [70]:
list_2=pd.read_csv('./MV_sum/mv_1213.csv')

In [71]:
Sum_list=pd.merge(list_1,list_2,how='inner',on='종목명')
Sum_list

,종목명,2012_E,2012_S,2012_G,2013_E,2013_S,2013_G,Diff_E,Diff_S,Diff_G,업종명,2012_종가,2013_종가
0,AK홀딩스,C,B이하,B+,C,B이하,B이하,NaN,NaN,NaN,기타금융,22350,40150
1,BYC,C,B이하,B이하,B,B이하,B이하,NaN,NaN,NaN,섬유의복,185000,188500
2,CJ,B,B이하,B이하,B,A,B이하,NaN,NaN,NaN,기타금융,106500,111000
3,CJ CGV,B,B이하,B이하,B,B이하,B이하,NaN,NaN,NaN,서비스업,33800,49950
4,CJ대한통운,B,B+,B이하,B+,A,B+,NaN,NaN,NaN,운수창고업,113500,92300
...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,효성,B+,B이하,B+,B+,B+,B+,NaN,NaN,NaN,기타금융,60100,71600
442,후성,B,B이하,B이하,C,B이하,B이하,NaN,NaN,NaN,화학,5120,4010
443,휴스틸,B,B이하,B+,B,B이하,B이하,NaN,NaN,NaN,철강금속,27400,19400
444,흥국화재,B,B이하,B이하,B,B이하,B이하,NaN,NaN,NaN,보험,4990,4525
445,흥아해운,B,B이하,B이하,B,B이하,B이하,NaN,NaN,NaN,운수창고업,1095,1595

In [72]:
## 12,13 E의 변화('object' --> 'float')
Sum_list['2012_E']=Sum_list['2012_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2013_E']=Sum_list['2013_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

## 12,13 S의 변화('object' --> 'float')
Sum_list['2012_S']=Sum_list['2012_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2013_S']=Sum_list['2013_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

## 12,13 G의 변화('object' --> 'float')
Sum_list['2012_G']=Sum_list['2012_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2013_G']=Sum_list['2013_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

## Diff값 채우기
Sum_list['Diff_E']= Sum_list['2013_E']-Sum_list['2012_E']
Sum_list['Diff_S']= Sum_list['2013_S']-Sum_list['2012_S']
Sum_list['Diff_G']= Sum_list['2013_G']-Sum_list['2012_G']
Sum_list['등락률']= (Sum_list['2013_종가']-Sum_list['2012_종가'])/ Sum_list['2012_종가']
Sum_list['연도']='12,13년'

In [78]:
#Sum_list.to_csv('Origin_1213.csv')

## Origin 1314데이터 만들기

In [79]:
list_1=pd.read_csv('./df_add_job/df_1314_add_job.csv')
list_2=pd.read_csv('./MV_sum/mv_1314.csv')
Sum_list=pd.merge(list_1,list_2,how='inner',on='종목명')

Sum_list['2013_E']=Sum_list['2013_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2014_E']=Sum_list['2014_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

Sum_list['2013_S']=Sum_list['2013_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2014_S']=Sum_list['2014_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

Sum_list['2013_G']=Sum_list['2013_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2014_G']=Sum_list['2014_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

## Diff값 채우기
Sum_list['Diff_E']= Sum_list['2014_E']-Sum_list['2013_E']
Sum_list['Diff_S']= Sum_list['2014_S']-Sum_list['2013_S']
Sum_list['Diff_G']= Sum_list['2014_G']-Sum_list['2013_G']
Sum_list['등락률']= (Sum_list['2014_종가']-Sum_list['2013_종가'])/ Sum_list['2013_종가']
Sum_list['연도']='13,14년'
Sum_list

,종목명,2013_E,2013_S,2013_G,2014_E,2014_S,2014_G,Diff_E,Diff_S,Diff_G,업종명,2013_종가,2014_종가,등락률,연도
0,AK홀딩스,1.0,1.5,1.5,1.0,1.5,1.5,0.0,0.0,0.0,기타금융,40150,71200,0.773350,"13,14년"
1,BYC,2.0,1.5,1.5,1.0,1.5,1.5,-1.0,0.0,0.0,섬유의복,188500,283500,0.503979,"13,14년"
2,CJ,2.0,4.0,1.5,2.0,4.0,3.0,0.0,0.0,1.5,기타금융,111000,174000,0.567568,"13,14년"
3,CJ CGV,2.0,1.5,1.5,1.0,3.0,1.5,-1.0,1.5,0.0,서비스업,49950,52400,0.049049,"13,14년"
4,CJ대한통운,3.0,4.0,3.0,3.0,4.0,3.0,0.0,0.0,0.0,운수창고업,92300,193000,1.091008,"13,14년"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,효성,3.0,3.0,3.0,2.0,3.0,1.5,-1.0,0.0,-1.5,기타금융,71600,63500,-0.113128,"13,14년"
453,후성,1.0,1.5,1.5,1.0,1.5,1.5,0.0,0.0,0.0,화학,4010,2495,-0.377805,"13,14년"
454,휴스틸,2.0,1.5,1.5,2.0,1.5,3.0,0.0,0.0,1.5,철강금속,19400,16650,-0.141753,"13,14년"
455,흥국화재,2.0,1.5,1.5,2.0,1.5,1.5,0.0,0.0,0.0,보험,4525,3860,-0.146961,"13,14년"
456,흥아해운,2.0,1.5,1.5,2.0,1.5,1.5,0.0,0.0,0.0,운수창고업,1595,2190,0.373041,"13,14년"

In [81]:
#Sum_list.to_csv('Origin_1314.csv')

## Origin 1415데이터 만들기

In [82]:
list_1=pd.read_csv('./df_add_job/df_1415_add_job.csv')
list_2=pd.read_csv('./MV_sum/mv_1415.csv')
Sum_list=pd.merge(list_1,list_2,how='inner',on='종목명')

Sum_list['2014_E']=Sum_list['2014_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2015_E']=Sum_list['2015_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

Sum_list['2014_S']=Sum_list['2014_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2015_S']=Sum_list['2015_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

Sum_list['2014_G']=Sum_list['2014_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2015_G']=Sum_list['2015_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

## Diff값 채우기
Sum_list['Diff_E']= Sum_list['2015_E']-Sum_list['2014_E']
Sum_list['Diff_S']= Sum_list['2015_S']-Sum_list['2014_S']
Sum_list['Diff_G']= Sum_list['2015_G']-Sum_list['2014_G']
Sum_list['등락률']= (Sum_list['2015_종가']-Sum_list['2014_종가'])/ Sum_list['2014_종가']
Sum_list['연도']='14,15년'
Sum_list

,종목명,2014_E,2014_S,2014_G,2015_E,2015_S,2015_G,Diff_E,Diff_S,Diff_G,업종명,2014_종가,2015_종가,등락률,연도
0,AK홀딩스,1.0,1.5,1.5,1.0,1.5,1.5,0.0,0.0,0.0,기타금융,71200,86000,0.207865,"14,15년"
1,BYC,1.0,1.5,1.5,1.0,1.5,1.5,0.0,0.0,0.0,섬유의복,283500,399000,0.407407,"14,15년"
2,CJ,2.0,4.0,3.0,2.0,4.0,3.0,0.0,0.0,0.0,기타금융,174000,240000,0.379310,"14,15년"
3,CJ CGV,1.0,3.0,1.5,2.0,1.5,1.5,1.0,-1.5,0.0,서비스업,52400,104000,0.984733,"14,15년"
4,CJ대한통운,3.0,4.0,3.0,3.0,3.0,3.0,0.0,-1.0,0.0,운수창고업,193000,195000,0.010363,"14,15년"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,후성,1.0,1.5,1.5,1.0,1.5,3.0,0.0,0.0,1.5,화학,2495,4175,0.673347,"14,15년"
473,휴비스,1.0,1.5,1.5,1.0,1.5,1.5,0.0,0.0,0.0,화학,12300,8490,-0.309756,"14,15년"
474,휴스틸,2.0,1.5,3.0,2.0,1.5,3.0,0.0,0.0,0.0,철강금속,16650,17900,0.075075,"14,15년"
475,흥국화재,2.0,1.5,1.5,3.0,1.5,1.5,1.0,0.0,0.0,보험,3860,4010,0.038860,"14,15년"
476,흥아해운,2.0,1.5,1.5,2.0,1.5,1.5,0.0,0.0,0.0,운수창고업,2190,1935,-0.116438,"14,15년"

In [83]:
#Sum_list.to_csv('Origin_1415.csv')

## Origin 1516데이터 만들기

In [84]:
list_1=pd.read_csv('./df_add_job/df_1516_add_job.csv')
list_2=pd.read_csv('./MV_sum/mv_1516.csv')
Sum_list=pd.merge(list_1,list_2,how='inner',on='종목명')

Sum_list['2015_E']=Sum_list['2015_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2016_E']=Sum_list['2016_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

Sum_list['2015_S']=Sum_list['2015_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2016_S']=Sum_list['2016_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

Sum_list['2015_G']=Sum_list['2015_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2016_G']=Sum_list['2016_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

## Diff값 채우기
Sum_list['Diff_E']= Sum_list['2016_E']-Sum_list['2015_E']
Sum_list['Diff_S']= Sum_list['2016_S']-Sum_list['2015_S']
Sum_list['Diff_G']= Sum_list['2016_G']-Sum_list['2015_G']
Sum_list['등락률']= (Sum_list['2016_종가']-Sum_list['2015_종가'])/ Sum_list['2015_종가']
Sum_list['연도']='15,16년'
Sum_list

,종목명,2015_E,2015_S,2015_G,2016_E,2016_S,2016_G,Diff_E,Diff_S,Diff_G,업종명,2015_종가,2016_종가,등락률,연도
0,AK홀딩스,1.0,1.5,1.5,2.0,1.5,1.5,1.0,0.0,0.0,기타금융,86000,61600,-0.283721,"15,16년"
1,BNK금융지주,5.0,4.0,1.5,5.0,3.0,1.5,0.0,-1.0,0.0,기타금융,14000,9290,-0.336429,"15,16년"
2,BYC,1.0,1.5,1.5,1.0,1.5,1.5,0.0,0.0,0.0,섬유의복,399000,436500,0.093985,"15,16년"
3,CJ,2.0,4.0,3.0,3.0,4.0,3.0,1.0,0.0,0.0,기타금융,240000,174500,-0.272917,"15,16년"
4,CJ CGV,2.0,1.5,1.5,1.0,3.0,1.5,-1.0,1.5,0.0,서비스업,104000,67800,-0.348077,"15,16년"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,후성,1.0,1.5,3.0,2.0,1.5,3.0,1.0,0.0,0.0,화학,4175,7770,0.861078,"15,16년"
495,휴비스,1.0,1.5,1.5,2.0,3.0,3.0,1.0,1.5,1.5,화학,8490,7170,-0.155477,"15,16년"
496,휴스틸,2.0,1.5,3.0,2.0,1.5,3.0,0.0,0.0,0.0,철강금속,17900,14600,-0.184358,"15,16년"
497,흥국화재,3.0,1.5,1.5,5.0,1.5,1.5,2.0,0.0,0.0,보험,4010,3455,-0.138404,"15,16년"
498,흥아해운,2.0,1.5,1.5,1.0,1.5,1.5,-1.0,0.0,0.0,운수창고업,1935,1680,-0.131783,"15,16년"

In [85]:
#Sum_list.to_csv('Origin_1516.csv')

## Origin 1617데이터 만들기

In [86]:
list_1=pd.read_csv('./df_add_job/df_1617_add_job.csv')
list_2=pd.read_csv('./MV_sum/mv_1617.csv')
Sum_list=pd.merge(list_1,list_2,how='inner',on='종목명')

Sum_list['2016_E']=Sum_list['2016_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2017_E']=Sum_list['2017_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

Sum_list['2016_S']=Sum_list['2016_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2017_S']=Sum_list['2017_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

Sum_list['2016_G']=Sum_list['2016_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2017_G']=Sum_list['2017_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

## Diff값 채우기
Sum_list['Diff_E']= Sum_list['2017_E']-Sum_list['2016_E']
Sum_list['Diff_S']= Sum_list['2017_S']-Sum_list['2016_S']
Sum_list['Diff_G']= Sum_list['2017_G']-Sum_list['2016_G']
Sum_list['등락률']= (Sum_list['2017_종가']-Sum_list['2016_종가'])/ Sum_list['2016_종가']
Sum_list['연도']='16,17년'
Sum_list

,종목명,2016_E,2016_S,2016_G,2017_E,2017_S,2017_G,Diff_E,Diff_S,Diff_G,업종명,2016_종가,2017_종가,등락률,연도
0,AJ네트웍스,1.0,1.5,1.5,2.0,1.5,1.5,1.0,0.0,0.0,서비스업,31250,7330,-0.765440,"16,17년"
1,AK홀딩스,2.0,1.5,1.5,2.0,1.5,1.5,0.0,0.0,0.0,기타금융,61600,67300,0.092532,"16,17년"
2,BNK금융지주,5.0,3.0,1.5,2.0,4.0,3.0,-3.0,1.0,1.5,기타금융,9290,9940,0.069968,"16,17년"
3,BYC,1.0,1.5,1.5,2.0,1.5,1.5,1.0,0.0,0.0,섬유의복,436500,320000,-0.266896,"16,17년"
4,CJ,3.0,4.0,3.0,4.0,4.0,1.5,1.0,0.0,-1.5,기타금융,174500,186500,0.068768,"16,17년"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,후성,2.0,1.5,3.0,1.0,1.5,3.0,-1.0,0.0,0.0,화학,7770,8930,0.149292,"16,17년"
516,휴비스,2.0,3.0,3.0,2.0,4.0,3.0,0.0,1.0,0.0,화학,7170,7800,0.087866,"16,17년"
517,휴스틸,2.0,1.5,3.0,2.0,1.5,1.5,0.0,0.0,-1.5,철강금속,14600,14600,0.000000,"16,17년"
518,흥국화재,5.0,1.5,1.5,4.0,1.5,1.5,-1.0,0.0,0.0,보험,3455,6180,0.788712,"16,17년"
519,흥아해운,1.0,1.5,1.5,2.0,1.5,1.5,1.0,0.0,0.0,운수창고업,1680,1255,-0.252976,"16,17년"

In [87]:
#Sum_list.to_csv('Origin_1617.csv')

## Origin 1718데이터 만들기

In [88]:
list_1=pd.read_csv('./df_add_job/df_1718_add_job.csv')
list_2=pd.read_csv('./MV_sum/mv_1718.csv')
Sum_list=pd.merge(list_1,list_2,how='inner',on='종목명')

Sum_list['2017_E']=Sum_list['2017_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2018_E']=Sum_list['2018_E'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

Sum_list['2017_S']=Sum_list['2017_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2018_S']=Sum_list['2018_S'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

Sum_list['2017_G']=Sum_list['2017_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})
Sum_list['2018_G']=Sum_list['2018_G'].map({
    'A+': 5,
    'A' : 4,
    'B+': 3,
    'B' : 2,
    'B이하' : 1.5,
    'C':1
})

## Diff값 채우기
Sum_list['Diff_E']= Sum_list['2018_E']-Sum_list['2017_E']
Sum_list['Diff_S']= Sum_list['2018_S']-Sum_list['2017_S']
Sum_list['Diff_G']= Sum_list['2018_G']-Sum_list['2017_G']
Sum_list['등락률']= (Sum_list['2018_종가']-Sum_list['2017_종가'])/ Sum_list['2017_종가']
Sum_list['연도']='17,18년'
Sum_list

,종목명,2017_E,2017_S,2017_G,2018_E,2018_S,2018_G,Diff_E,Diff_S,Diff_G,업종명,2017_종가,2018_종가,등락률,연도
0,AJ네트웍스,2.0,1.5,1.5,1.0,1.5,1.5,-1.0,0.0,0.0,서비스업,7330,4555,-0.378581,"17,18년"
1,AK홀딩스,2.0,1.5,1.5,1.0,1.5,1.5,-1.0,0.0,0.0,기타금융,67300,44600,-0.337296,"17,18년"
2,BNK금융지주,2.0,4.0,3.0,NaN,3.0,1.5,NaN,-1.0,-1.5,기타금융,9940,7590,-0.236419,"17,18년"
3,BYC,2.0,1.5,1.5,3.0,1.5,1.5,1.0,0.0,0.0,섬유의복,320000,233500,-0.270313,"17,18년"
4,CJ,4.0,4.0,1.5,4.0,5.0,1.5,0.0,1.0,0.0,기타금융,186500,109000,-0.415550,"17,18년"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,후성,1.0,1.5,3.0,2.0,1.5,3.0,1.0,0.0,0.0,화학,8930,8730,-0.022396,"17,18년"
555,휴비스,2.0,4.0,3.0,3.0,3.0,3.0,1.0,-1.0,0.0,화학,7800,7370,-0.055128,"17,18년"
556,휴스틸,2.0,1.5,1.5,2.0,1.5,1.5,0.0,0.0,0.0,철강금속,14600,11250,-0.229452,"17,18년"
557,흥국화재,4.0,1.5,1.5,NaN,1.5,1.5,NaN,0.0,0.0,보험,6180,4825,-0.219256,"17,18년"
558,흥아해운,2.0,1.5,1.5,1.0,1.5,1.5,-1.0,0.0,0.0,운수창고업,1255,394,-0.686056,"17,18년"

In [89]:
S#um_list.to_csv('Origin_1718.csv')